{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "alloy-dynamic-processors.fullname" . }}
  labels:
    {{- include "alloy-dynamic-processors.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
rules:
{{- with .Values.rbac.rules }}
{{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "alloy-dynamic-processors.fullname" . }}
  labels:
    {{- include "alloy-dynamic-processors.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "alloy-dynamic-processors.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "alloy-dynamic-processors.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}