{{- if and .Values.grafanaCloud.enabled (not .Values.grafanaCloud.credentials.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alloy-dynamic-processors.grafanaCloudSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alloy-dynamic-processors.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
  {{- with (include "alloy-dynamic-processors.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  instance-id: {{ .Values.grafanaCloud.credentials.instanceId | b64enc | quote }}
  api-key: {{ .Values.grafanaCloud.credentials.apiKey | b64enc | quote }}
  prometheus-url: {{ .Values.grafanaCloud.credentials.prometheusUrl | b64enc | quote }}
  tempo-url: {{ .Values.grafanaCloud.credentials.tempoUrl | b64enc | quote }}
  loki-url: {{ .Values.grafanaCloud.credentials.lokiUrl | b64enc | quote }}
{{- end }}